name: blurspot
favicon: null
layout_spectrum: 0.46596
typography_spectrum: 0.57817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75128123-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
